openapi: 3.0.0
info:
  title: Smatjnester
  version: '1.0'
  description: Smatjnester REST APIs
servers:
  - url: 'http://localhost:3000/api/v1'
    description: localhost
paths:
  /login:
    post:
      summary: Login
      operationId: post-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - description: 'apiToken: false'
                    properties:
                      accessToken:
                        type: string
                      refreshToken:
                        type: string
                  - properties:
                      apiToken:
                        type: string
                    description: 'apiToken: true'
                type: object
              examples:
                success:
                  value:
                    accessToken: GTZ525AIJJDYNPOLDIJTHTBNNTHBSTARWQGFH
                    refreshToken: POSLJTGTYRQFJSDYYGYJGHQETUYGJJBJSJG
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                Error:
                  value:
                    message: Invalid Credentials.
      tags:
        - Authentication
      description: Authentication API
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                apiToken:
                  type: boolean
              required:
                - username
                - password
                - apiToken
            examples:
              Request:
                value:
                  username: xyz@abc.com
                  password: '123456'
        description: Pass username & password.
components:
  schemas: {}
  securitySchemes: {}
